# This replaces your existing "actions/jekyll-build-pages" step

- name: Setup Ruby
  # Use an action to set up the Ruby environment
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: '3.1' # Use the version compatible with jekyll-scholar

- name: Install dependencies
  # This step installs the required gems, including jekyll-scholar
  run: |
    gem install bundler
    bundle config path vendor/bundle
    bundle install --jobs 4 --retry 3

- name: Build Jekyll site
  # This runs the build command directly, using the installed gems
  run: bundle exec jekyll build --future --destination ./_site
  # The '--destination ./_site' flag matches the output of your original action

- name: Upload site artifacts
  # Use this action to save the built site
  uses: actions/upload-pages-artifact@v3
  with:
    path: ./_site